server.port: 8888


spring.datasource.url: jdbc:mysql://localhost:3306/guxuan?useUnicode=true&characterEncoding=utf8&useSSL=false
spring.datasource.username: root
spring.datasource.password: 123456

spring.application.name: spirng-boot-rabbitmq-sender
spring.rabbitmq.host: 127.0.0.1
spring.rabbitmq.port: 5672
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest

gu.cache.cron: 0 0 0 0/1 * *